title = "spy16"
theme="moded-ink"
baseURL = "https://spy16.in/"
paginate = 5
copyright = "Â© Shivaprasad Bhat"
languageCode = "en-us"

# Syntax Highlighting
pygmentsstyle = "emacs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# External Plugins/Integrations
googleAnalytics = "G-E57FGYYMSF"
disqusShortname = "spy16-in"

# Site parameters
[params]
mode = "auto" # "dark" or "auto"
avatar = "https://s.gravatar.com/avatar/07d369134a5308bfc99d1d5ae985e7f1?s=80"
subtitle = "Poor attempts to convey my thoughts."
featherIconsCDN = true
disableDisqusTypes = ["page", "not_post"]

[author]
name = "Shivaprasad Bhat"

# Navigation menu.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About Me"
url = "/about"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/spy16"

[[params.social]]
name = "Github"
icon = "linkedin"
url = "https://www.linkedin.com/in/shivaprasadbhat/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"

[related]
includeNewer = false
threshold = 80
toLower = false

[[related.indices]]
name = 'tags'
weight = 100

[[related.indices]]
name = 'date'
weight = 10
